### PR TITLE
Multi language support (fixes #29)

### LINKED ISSUE #29: Support other languages
The reason for #28 was that I was using Scala to write the benchmark. It would be nice to have support for the other JVM languages, just like JMH itself.

### PR DESCRIPTION
**Pull request by vyazelenko**
This PR implements multi-language support and fixes #29. Complete list of changes:
* Support multiple language not just Java
* Small typo for `CSV` case in `ResultFormatType`
* Move test project to src/test/resources
* Adds test dependency on `gradleTestKit()`

/cc @aalmiray

### CODE REVIEW

**Comment by vyazelenko** [comment]
Thanks @aalmiray!

**Comment by eshepelyuk** [comment]
Can this fix be released officially soon ?

**Comment by vyazelenko** [comment]
@aalmiray don't you think it's time for *0.3.0* release? ;)

**Comment by aalmiray** [comment]
Yes, I do! I pinged @melix to figure out what can be done to push the next release.

**Pull request merged**
