### PR TITLE
Do not access 'project.zipTree' in mapping closure

### LINKED ISSUE #229: jmhJar task is not compatible with Gradle configuration cache
**Describe the bug**
The plugin causes an error if the experimental Gradle configuration cache is enabled.

**To Reproduce**
Run `gradle jmh --configuration-cache` in a project that uses this plugin.

The output will include an error along the lines of:
```
FAILURE: Build failed with an exception.

* What went wrong:
Configuration cache problems found in this build.

1 problem was found storing the configuration cache.
- Task `:project:jmhJar` of type `org.gradle.api.tasks.bundling.Jar`: cannot serialize object of type 
'org.gradle.api.internal.project.DefaultProject', a subtype of 'org.gradle.api.Project', as these are not
supported with the configuration cache.
  See https://docs.gradle.org/7.6-rc-3/userguide/configuration_cache.html#config_cache:requirements:disallowed_types
```
This appears to happen for both shadow and non-shadow forms of the jar task.

There's an easy and obvious workaround, of course -- "don't do that" -- but it becomes a chore if the configuration cache is turned on in gradle.properties.

### PR DESCRIPTION
**Pull request by jjohannes**
This is not supported by the Configuration Cache. Instead, we inject an ArchiveOperations service.

Fixes #229

### CODE REVIEW

**Comment by jjohannes** [comment]
No problem. Happy I figured this out. I am also not super happy with the subclass.

I tried injecting via the plugin already. It's not working. The service property can't be found when the code in the closure executes (if CC is turned on).

I think this is, because the code executes **after** the state has been loaded from the cache. Which is the reason why there is a problem in the first place. At that point, the plugin context is not available anymore.

**Comment by jjohannes** [comment]
It can be injected via the plugin. "Just" need to store a reference in a variable while we can.

Updated the PR – PTAL.

**Comment by jjohannes** [comment]
The test also starts failing (on master) with newer Gradle versions. Not sure anymore if what was reported in #261 is exactly this issue. But in any case this is an issue with Gradle `8.5`.

**Comment by melix** [comment]
@jjohannes can you allow edits on your PR?

**Comment by jjohannes** [comment]
> can you allow edits on your PR?

Should be turned on.

**Comment by melix** [comment]
Strange, I get a permission denied :thinking:

**Comment by jjohannes** [comment]
Strange. The flag is set here in my UI. Feel free to just copy the solution into a new PR/branch.

**Comment by melix** [comment]
My bad, had a typo in the branch name

**Comment by jjohannes** [comment]
Thank you @melix!

**Pull request merged**
