### PR TITLE
Renovate updates

### PR DESCRIPTION
**Pull request by Goooler**

### CODE REVIEW

**Comment by melix** [comment]
This plugin needs to remain compatible with older Gradle releases, Gradle 8 is simply too recent.

**Comment by Goooler** [comment]
I noticed you updated [sheet](https://github.com/melix/jmh-gradle-plugin#what-plugin-version-to-use), if so I'll revert some changes.

**Comment by melix** [comment]
Yes, because the README works the other way around, it tells you which version of the plugin you need to use for each Gradle version. but the higher versions of the plugins still support older versions.

**Review by melix — APPROVED** [review]
Thanks!

**Pull request merged**
