### PR TITLE
Fix a bug where benchmarkParameters are not respected

### PR DESCRIPTION
**Pull request by jrhee17**
**Motivation**

Benchmark fails to run due to an extra space

```
> Task :jmh FAILED
[-bm, thrpt,ss, -foe, 1, -gc, 0,  -p, a=a, -rf, csv, -rff, /private/var/folders/5t/dnxsrx2d3r3c602x4z01t2vw0000gn/T/spock_Executes_benchmarks_0_temporaryFolder6367835791579630067/build/reports/benchmarks.csv]
No matching benchmarks. Miss-spelled regexp?
```

**Modification**
- Remove the extra whitespace and add a functional test

### CODE REVIEW

**Comment by mkjois** [comment]
@melix I'm running into this as well. Can we get this merged and released?

**Review by melix — APPROVED** [review]

**Comment by melix** [comment]
Good catch, thank you!

**Comment by mkjois** [comment]
@melix Thanks! What's your release schedule like? Just want to get a sense for when I can expect 0.6.6

**Comment by mkjois** [comment]
Fantastic, amazing plugin too btw!

**Pull request merged**
